### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by modin-gamin** [Hyperclaw79/PokeBall-SelfBot-Poketwo-Automation#215]
C:\Users\logan\OneDrive\Desktop\PokeBall-SelfBot-Poketwo-Automation-master>py -3 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 2, in <module>
    from pokeball import PokeBall
  File "C:\Users\logan\OneDrive\Desktop\PokeBall-SelfBot-Poketwo-Automation-master\pokeball.py", line 167
    return f"{name} -> {number} -> {level}"
                                          ^
SyntaxError: invalid syntax

C:\Users\logan\OneDrive\Desktop\PokeBall-SelfBot-Poketwo-Automation-master>timeout -1

helpp???

**Comment by modin-gamin** [comment]
C:\Users\logan\OneDrive\Desktop\PokeBall-SelfBot-Poketwo-Automation-master>py -3 launcher.py
Traceback (most recent call last):
  File "C:\Users\logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\http.py", line 293, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\http.py", line 247, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "launcher.py", line 19, in <module>
    bot.run()
  File "C:\Users\logan\OneDrive\Desktop\PokeBall-SelfBot-Poketwo-Automation-master\pokeball.py", line 51, in run
    super().run(self.configs['token'], bot=False)
  File "C:\Users\logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 718, in run
    return future.result()
  File "C:\Users\logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 697, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 660, in start
    await self.login(*args, bot=bot)
  File "C:\Users\logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 509, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\http.py", line 297, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.


and this

**Comment by Hyperclaw79** [comment]
The first one seems to be cause of wrong version of Python. The second one,
as visible in the error, you are using a wrong Discord token. Search
YouTube for "how to get Discord selfbot token". And if you're using 2Factor
Authentication, then first login on the Discord app on the same pc on which
you're trying the bot.

P.S. Please refer to the closed issues before opening a new one as it might
already have a solution.
